### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by netstx** [texduino/Raspberry_RV-3028-C7#1]
Hi,

I was interested in using the RTC on a Raspberry Pi 4, wondering if you already have the library for it and would be releasing it soon, or if it's still under development.

Not trying to rush, just curious. Thanks!

**Comment by texduino** [comment]
Hello,

 

If you are asking about python library, yes we have it and it should be up on github in the next few days.

 

 

Thank you for asking!

 

Support@TexDuino.com <mailto:Support@TexDuino.com> 

www.TexDuino.com <http://www.TexDuino.com> 

 

 

 

 

 

 

From: Rafael ***@***.*** 
Sent: Wednesday, April 21, 2021 5:20 PM
To: texduino/Raspberry_RV-3028-C7 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [texduino/Raspberry_RV-3028-C7] First release (#1)

 

Hi,

I was interested in using the RTC on a Raspberry Pi 4, wondering if you already have the library for it and would be releasing it soon, or if it's still under development.

Not trying to rush, just curious. Thanks!

**Comment by netstx** [comment]
Thanks!

**Comment by texduino** [comment]
Rafael,

 

We added some basic instructions on connecting the TexDuino RV-3028-C7 breakout board to a Raspberry Pi for using it as a RTC. 

While we will be adding to the instructions, hope this will get you going for now. If you have any questions please email us.

 

Thank you,

 

Support@TexDuino.com <mailto:Support@TexDuino.com> 

www.TexDuino.com <http://www.TexDuino.com> 

 

 

From: Rafael ***@***.*** 
Sent: Wednesday, April 21, 2021 5:20 PM
To: texduino/Raspberry_RV-3028-C7 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [texduino/Raspberry_RV-3028-C7] First release (#1)

 

Hi,

I was interested in using the RTC on a Raspberry Pi 4, wondering if you already have the library for it and would be releasing it soon, or if it's still under development.

Not trying to rush, just curious. Thanks!

**Comment by netstx** [comment]
Thanks!
